port: 8080

# Dependencies
kube-prometheus-stack:
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      scrapeInterval: 10s

cadvisor:
  metrics:
    enabled: true
    interval: 5s
