apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: ml-simulation
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          limits:
            memory: 32M
            cpu: 50m
          requests:
            memory: 32M
            cpu: 25m
