kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.port }}
