{
 "title": "CPU Usage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{job=\"cadvisor\"},container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\"},container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\", container_label_io_kubernetes_pod_name=\"$pod\"},container_label_io_kubernetes_container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=\"$namespace\",\n            job=\"cadvisor\"\n        }[1m]\n    )\n) by (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n) / sum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=\"$namespace\",\n        job=\"cadvisor\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=\"$namespace\",\n        job=\"cadvisor\"\n    }\n) by (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n    container_cpu_cfs_throttled_seconds_total\n    {\n        container_label_io_kubernetes_pod_namespace=\"$namespace\",\n        job=\"cadvisor\"\n    }[1m]\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage in milli-cores with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_container_name=\"$container\",\n            container_label_io_kubernetes_pod_name=\"$pod\",\n            container_label_io_kubernetes_pod_namespace=\"$namespace\",\n            job=\"cadvisor\"\n        }[1m]\n    )\n) by (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n) * 1000",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "kube_pod_container_resource_limits\n{\n    pod=\"$pod\",\n    namespace=\"$namespace\",\n    container=\"$container\",\n    unit=\"core\"\n} * 1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests\n{\n    pod=\"$pod\",\n    namespace=\"$namespace\",\n    container=\"$container\",\n    unit=\"core\"\n} * 1000",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}