# Only has to be used, if monitoring kubernetes-internas is important
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        bind-address: "0.0.0.0"
        show-hidden-metrics-for-version: "1.26"
        authorization-always-allow-paths: /healthz,/readyz,/livez,/metrics,/metrics/resources  # if the /metrics/resources endpoint is to be scraped, the kube-scheduler ServiceMonitor has to be adapted to point to the correct http-path
    controllerManager:
      extraArgs:
        bind-address: "0.0.0.0"