global:
  scrape_interval: 5s
scrape_configs:
  - job_name: ml-simulation
    static_configs:
      - targets:
          - ml-simulation:8080
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
